import {createSlice} from '@reduxjs/toolkit';
const initialState = {
  user: {},
  balance: 0,
  currentPlan: {},
  allService: [],
  currentService: {},
  AllCapedData: [],
  language: 'ar',
  showedModal: true,
  languageString: {
    aboutNessma: 'عن نسمة',
    account: 'حسابي',
    active: 'فعال',
    activeTickets: 'طلبات نشطة',
    addMoney: 'تعبئة الرصيد',
    addYourComments: 'أضف تعليقاتك',
    alreadyHaveAnAccount: 'أنا لدي حساب',
    alreadySubmit: 'إرسال الاستعراض بالفعل',
    bal: 'رصيدك',
    balanceAfter: 'رصيدك بعد',
    balanceBefore: 'رصيدك قبل',
    basic: 'بيانتي',
    bytes: 'بايت',
    changePlan: 'تغير الباقة',
    changeTariff: 'تغير الباقة',
    contract: 'عقد الاشتراك',
    createFeedback: 'إنشاء ملاحظات',
    createTicket: 'إنشاء طلب الدعم الفني',
    creditCard: 'سداد- تداول - إدفع لي - معاملات - موبي كاش',
    dashboard: 'لوحة التحكم',
    data: 'البيانات',
    daysLeft: 'الايام المتبقية',
    deleteAccount: 'نسمة نت',
    description: 'وصف',
    document: 'مستندات',
    download: 'التحميل',
    email: 'البريد الإلكتروني',
    enterYourAmount: 'أدخل المبلغ الخاص بك',
    enterYourLoginAndEmail: 'أدخل معلومات تسجيل الدخول والبريد الإلكتروني',
    enterYourPassword: 'أدخل الرقم السري',
    enterYourUserId: 'أدخل رقم العقد',
    enterYourVoucherCode: 'أدخل كود التعبئة',
    faq: 'الاسئلة الشائعة',
    feedback: 'أضف تقييم',
    fillYourDetail: 'املأ بياناتك وسنعاود الاتصال بك.',
    filter: 'تطبيق',
    forgotPassword: 'هل نسيت كلمة السر',
    frequentlyAskedQuestions: 'أسئلة مكررة',
    from: 'من',
    fullName: 'الاسم',
    history: 'تاريخ',
    idProof: 'إثبات الهوية',
    insufficientBalance: 'ليس لديك رصيد كافٍ',
    invoiceDue: 'الفاتورة المستحقة في',
    invoices: 'الفواتير',
    language: 'اللغة',
    limited: 'الباقات المحدودة',
    location: 'الموقع',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    LYD: 'دينار',
    main: 'الرئيسية',
    more: 'أكثر',
    newPlan: 'الباقة الجديدة',
    newPlanStartDate: 'تاريخ بدء الباقة الجديدة',
    noDataFound: 'لاتوجد بيانات',
    notAMemberYet: 'لست مشترك',
    notification: 'إشعار',
    nowYouDoNotHave:
      'الآن ليس لديك طلبات نشطة. أضف طلب، اضغط على زر إنشاء الطلب',
    ok: 'نعم',
    orderNow: 'اطلب الان',
    payments: 'المدفوعات',
    payNow: 'ادفع الآن',
    phoneNumber: 'رقم التليفون',
    planExpireOn: 'تنتهي الصلاحية في',
    plans: 'الباقات',
    pleaseCheckYourNetwork: 'يرجى التحقق من الشبكة',
    pleaseCheckYourRefillCode: 'يرجى التحقق من كود التعبئة الخاص بك مرة أخرى',
    pleaseEnterMessage: 'الرجاء إدخال الرسالة',
    pleaseEnterRefillCode: 'الرجاء إدخال كود التعبئة',
    pleaseEnterSubject: 'الرجاء إدخال الموضوع',
    pleaseEnterYourEmail: 'الرجاء أدخل بريدك الإلكتروني',
    pleaseEnterYourPassword: 'من فضلك أدخل رقمك السري',
    pleaseEnterYourPhoneNumber: 'يرجى إدخال رقم الهاتف الخاص بك',
    pleaseEnterYourUserId: 'الرجاء إدخال رقم العقد الخاص بك',
    pleaseEnterYourUsername: 'الرجاء إدخال اسم المستخدم',
    pleaseRateTheApplicationFunctionality: 'يرجى تقييم وظائف التطبيق',
    pleaseRateTheDesign: 'يرجى تقييم تصميم التطبيق',
    pleaseSelectPriorityType: 'الرجاء تحديد نوع الأولوية',
    pleaseSelectSupportType: 'الرجاء تحديد نوع الدعم',
    pleaseSelectThePlanFirst: 'الرجاء تحديد الباقة أولا',
    pleaseSelectYourPlan: 'الرجاء تحديد الباقة',
    pleaseUpdateYourEmail: 'الرجاء تحديث البريد الإلكتروني الخاص بك أولا',
    pleaseUpdateYourPhoneNumber: 'يرجى تحديث رقم هاتفك أولا',
    price: 'السعر',
    priority: 'أولوية',
    privacyPolicy: 'سياسة الخصوصية',
    processInfo: 'معلومات عن العملية',
    profile: 'حساب تعريفي',
    profileUpdateSuccessfully: 'تم تحديث الملف الشخصي بنجاح',
    recentUsage: 'سجل الاستهلاك',
    redeemRefillCard: 'بطاقة إعادة التعبئة',
    refillCardSuccessfully: 'تم اضافة الرصيد بنجاح',
    remaining: 'متبقي',
    reset: 'إعادة الظبط',
    resetCustomerPassword: 'إعادة تعيين كلمة المرور',
    searchLanguage: 'لغة البحث',
    searchPlan: 'خطة البحث',
    selectDate: 'اختار التاريخ',
    selectLanguage: 'اختار اللغة',
    selectPlan: 'اختر الباقة',
    selectPriority: 'حدد الأولوية',
    selectType: 'اختر صنف',
    service: 'خدمة',
    signUp: 'اشترك الان',
    somethingWentWrong: 'هناك خطأ ما',
    speedUpto: 'السرعة تصل إلى',
    statistics: 'إحصائيات',
    status: 'الحالة',
    street: 'العنوان',
    subject: 'موضوع',
    submit: 'إرسال',
    support: 'الدعم الفني',
    thereAreNoDocument: 'لا يوجد مستند الآن يرجى الاتصال بالدعم الفني',
    thereIsNoHistory: 'لا يوجد تاريخ الآن',
    thisIsNotValidPlan: 'هذه ليست باقة صالحة. الرجاء تغيير الباقة',
    ticketCreatedSuccessfully: 'تم إنشاء طلب الدعم الفني بنجاح',
    ticketRaised: 'تم فتح الطلب',
    topUp: 'الحصة الإضافية',
    topUpPlan: 'الحصة الاضافية',
    total: 'المجموع',
    transactions: 'المعاملات',
    type: 'يكتب',
    typeHere: 'أكتب هنا',
    unLimited: 'الباقات اللامحدودة',
    update: 'تحديث',
    uploaded: 'الرفع',
    userInfo: 'معلومات المستخدم',
    vouchers: 'بطاقات نسمة نت',
    welcome: 'مرحباً',
    writeMessage: 'اكتب الطلب',
    yourCurrency: 'رصيدك',
    yourPaymentReceipt: 'تم تنزيل إيصال الدفع الخاص بك بنجاح',
    yourPaymentSuccess: 'دفعتك ناجحة',
    yourRequestSubmit: 'تم تقديم طلبك بنجاح سنتواصل معك قريبا',
  },
};

export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setUserDetail: (state, action) => {
      state.user = action.payload;
    },
    setUserBalance: (state, action) => {
      state.balance = action.payload;
    },
    setCurrentPlan: (state, action) => {
      state.currentPlan = action.payload;
    },
    setAllUserService: (state, action) => {
      state.allService = action.payload;
    },
    setCurrentUserService: (state, action) => {
      state.currentService = action.payload;
    },
    getAllCapedData: (state, action) => {
      state.AllCapedData = action.payload;
    },
    setAppLanguage: (state, action) => {
      state.language = action.payload;
    },
    setLanguageString: (state, action) => {
      state.languageString = action.payload;
    },
    setShowedModal: (state, action) => {
      state.showedModal = action.payload;
    },
  },
});

export const {
  setUserDetail,
  setCurrentPlan,
  setUserBalance,
  setAllUserService,
  setCurrentUserService,
  getAllCapedData,
  setAppLanguage,
  setLanguageString,
  setShowedModal,
} = userSlice.actions;

export default userSlice.reducer;
